version: '3.1'
services:
  postgres:
    image: postgres:latest
    restart: always
    networks:
      - redmine
    volumes:
      - /home/<your_path_here>/data/postgres-data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_PASSWORD=<your_password_here>'
      - 'POSTGRES_DB=redmine'
  redmine:
    image: redmine:latest
    restart: always
    networks:
      - redmine
    volumes:
      - /home/<your_path_here>/data/redmine-data:/usr/src/redmine/files
    ports:
      - 10080:3000
    environment:
      - 'REDMINE_DB_POSTGRES=postgres'
      - 'REDMINE_DB_DATABASE=redmine'
      - 'REDMINE_DB_PASSWORD=<your_password_here>'
volumes:
  postgres-data:
  redmine-data:
networks:
  redmine:
    driver: bridge